# Generated by Django 5.2 on 2025-04-19 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='imagem_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
